The view mode part should provide an api#5
aannenko/noughts-and-crosses pull request #10
Opened 2017-03-23 15:18 UTC by KassandraA

Pull request for view-model API task.

2017-03-23 20:07 UTC, aannenko commented on source/view-model.js
> +    setPlayer: function(key, value){
**Error**: looks like this method will find a specified key in the first player.
**Suggestion**: fix the error (make the method change player's properties based on the player's name) and rename the method to make it reflect its purpose better.
**Expected result**: `setPlayerProperty(playerName, propertyName, propertyValue)`, where `playerName` allows the method to find a player by their name, `propertyName` specifies which property to change and `propertyValue` specifies a value for this property. In the future tasks this method will be updated to find players by their IDs.

2017-03-23 20:07 UTC, aannenko commented on source/view-model.js
> +    getPlayer: function(){
Please rename this method to `getPlayers` and add two more methods with the same name `getPlayer` that would return specific player by their name or number in the `players` array.

2017-03-24 13:37 UTC, KassandraA commented on source/view-model.js
> +    setPlayer: function(key, value){
Done

2017-03-24 13:38 UTC, KassandraA commented on source/view-model.js
> +    getPlayer: function(){
Done. But you'd better see it first without pull request.

2017-03-26 10:04 UTC, aannenko requested changes

2017-03-26 10:04 UTC, aannenko commented on source/view-model.js
> +        {type : 'human', name : 'First', symbol : 'X'},
Could you please give the first player a better name ("Player", maybe)?

2017-03-26 10:08 UTC, KassandraA commented on source/view-model.js
> +        {type : 'human', name : 'First', symbol : 'X'},
Done

2017-03-26 10:08 UTC, aannenko approved these changes

2017-03-26 10:10 UTC, merged