Adjust view model and view to model task #12
aannenko/noughts-and-crosses pull request #14
Opened 2017-06-21 18:21 UTC by KassandraA

2017-06-22 18:27 UTC, aannenko requested changes
Lots of problems with view.js. Please see the comments.

2017-06-22 18:27 UTC, aannenko commented on source/js/model.js
> +                prop = prop.toLowerCase();
Let's move this string up one level. It should be right before the first `if`

2017-06-22 18:27 UTC, aannenko commented on source/js/model.js
> +    function isCellInField(cellObject) {
Can we move this function to the Field object? It can have the same name but different set of parameters `(row, column)`

2017-06-22 18:27 UTC, aannenko commented on source/js/model.js
> +                next = [{row: currentCell[0].row - 1, col: currentCell[0].col, obj: currentCell[0].obj}];
Can we move these objects out of arrays?

2017-06-22 18:27 UTC, aannenko commented on source/js/model.js
> +    };
Please add empty line after this line.

2017-06-22 18:27 UTC, aannenko commented on source/js/model.js
> +    this.refreshFieldCells = function() {
Game object should not have this function. `_field.refreshFieldCells()` should be executed only once when new Game is created.

2017-06-22 18:27 UTC, aannenko commented on source/js/view-model.js
> +    this.refreshFieldCells = function() {
This function should not be in the ViewModel. `refreshFieldCells` should only get executed in the Game object when it is created.

2017-06-22 18:27 UTC, aannenko commented on source/js/model.js
> +                else if (prop === 'symbol' && getAvailableSymbolList().includes(value)) {
Let's use `_availableSymbolList` array everywhere in the GameDataManager object. If we use `getAvailableSymbolList()` inside the object, we perform a redundant operation of copying the array.

2017-06-22 18:27 UTC, aannenko commented on source/js/model.js
> +        this.getAvailableSymbolList = function() {
Please make this function return a copy of the array, not the array itself.

2017-06-22 18:27 UTC, aannenko commented on source/js/view.js
> +let playerInstanceBlock = document.getElementById('player_instance_block');
Can we rename this and the next variable to make them correspond the naming conventions? The name of the first one should tell us that this element contains other player instances, the name of the second one should represent an array.

2017-06-22 18:27 UTC, aannenko commented on source/js/view.js
> +function updateCellContent() {
Name of this function should tell us that the function updates all cells according to the info from the ViewModel.

2017-06-22 18:27 UTC, aannenko commented on source/js/model.js
> +        function getAvailableSymbolList() {
Please remove this function. We already have it on line 50.

2017-06-22 18:27 UTC, aannenko commented on source/js/view.js
> +function createSymbolList(element) {
Can we refactor this function to make it update available symbols for all players when a player is added or when any player's symbol is changed? We should also give it a corresponding name.

2017-06-22 18:27 UTC, aannenko commented on source/js/view.js
> +            occupiedCells[r][c] = fieldCellsArr[r][c];
1. Can we set `occupiedCells[r][c]` to `true` and check if it is `true` instead of `fieldCellsArr[r][c] !== occupiedCells[r][c]`? This would simplify the check and will make the code more robust.
2. This line of code should be inside the `if` (one line up).

2017-06-22 18:27 UTC, aannenko commented on source/js/view.js
> +    let list = viewModel.getPlayerList();
Can we give this variable a proper name? Will playersList fit?

2017-06-22 18:27 UTC, aannenko commented on source/js/view.js
> +function createOccupiedCells(rows, columns) {
Can we give this function a better name? initializeOccupiedCellsArray?

2017-06-22 18:27 UTC, aannenko commented on source/js/view.js
> +    let fieldTbody = playField.appendChild(document.createElement('tbody'));
If we add `playField.innerHTML = ''` before this line, we can get rid of the `updatePlayerField` function.

2017-06-22 18:27 UTC, aannenko commented on source/js/view.js
> +function updatePlayerField() {
This function is redundant. Please see the comment on the line 100.

2017-06-22 18:27 UTC, aannenko commented on source/js/view.js
> +function getPlayerInstanceTemplate(player) {
Can we give this function a better name? It does not return anything so it shouldn't start from "get". Also it works with template but the template is not the end result of its execution. Maybe addPlayerInstance would fit better?

2017-06-22 18:27 UTC, aannenko commented on source/js/view.js
> +        createSymbolList(playerElem.querySelector('.form-group .player_symbol'));
This function shouldn't be called here. A better place for it is in the end of the `window.onload` code.

2017-06-22 18:27 UTC, aannenko commented on source/js/view.js
> +    if (playField.hasChildNodes()) {
We don't need this check.

2017-06-22 18:27 UTC, aannenko commented on source/js/view.js
> +function reloadGame() {
This function and the button it backs are not needed.

2017-06-22 18:27 UTC, aannenko commented on source/js/view.js
> +function init(rows, columns) {
The content of this function should be moved to the `startGame` function because this is the only place where we use it.

2017-06-22 18:27 UTC, aannenko commented on source/js/view.js
> +    }
Available symbols should be updated for all players here too.

2017-06-22 18:27 UTC, aannenko commented on source/js/view.js
> +function updateSymbolList() {
Please remove this function and see the comment for the `createSymbolList` function

2017-06-23 13:25 UTC, KassandraA commented
All done.

2017-06-23 20:15 UTC, aannenko requested changes

2017-06-23 20:15 UTC, aannenko commented on source/js/model.js
> +            let rows = gameDataManagerSingleton.getInstance().getRows();
This and the next line should be inside the `if` below.

2017-06-23 20:15 UTC, aannenko commented on source/js/view-model.js
> +        return getGameState().currentStatus;
`getGameState` function has only one line. So why don't we use its body inside `getFieldCells` and `getCurrentStatus` and remove it completely?

2017-06-23 20:15 UTC, aannenko commented on source/js/view.js
> +    let list = viewModel.getPlayersCollection();
Why don't we put this line right before the `for`? In this case it will be closer to where it is used.

2017-06-23 20:15 UTC, aannenko commented on source/js/view.js
> +    let symbolsCollection = document.getElementsByClassName('player_symbol');
Can we give this variable a better name? Would `inputsCollection` fit?

2017-06-23 20:15 UTC, aannenko commented on source/js/view.js
> +    let list = getAvailableSymbolsList();
Can we come up with a better name for this variable? `availableSymbols` maybe?

2017-06-23 20:15 UTC, aannenko commented on source/js/view.js
> +        let selectedSymbol = symbolsCollection[k].options[symbolsCollection[k].selectedIndex];
Can we give this variable a name that would represent its relation to an input?

2017-06-23 20:15 UTC, aannenko commented on source/js/view.js
> +    playField.innerHTML = '';
This line seems to fit the `createPlayField' function better. You can put it there as a first line of code.

2017-06-23 20:15 UTC, aannenko commented on source/js/view.js
> +    let statusField = document.getElementById("gameStatus");
Can we move this variable to this document?

2017-06-23 20:25 UTC, aannenko commented
There are still several minor issues but the code is now much cleaner and easier to read.
Good job!

2017-06-25 10:05 UTC, KassandraA commented
Changes done.

2017-06-26 17:43 UTC, merged