New design for game #16
aannenko/noughts-and-crosses pull request #23
Opened 2017-12-01 20:40 UTC by KassandraA

The task includes new UI and some bug fixes.

2017-12-01 22:03 UTC, aannenko requested changes
Several minor changes required and Edge support should be fixed. Aside from that - great job!

2017-12-01 22:03 UTC, aannenko commented on source/Tests/index-old.html
> +<!DOCTYPE html>
According to its name, this file should not be included in this pool request and in the repo itself.

2017-12-01 22:03 UTC, aannenko commented on .gitignore
> +style-old.css
Please remove files from the repo and from the .gitignore that should not be in the repo.

2017-12-01 22:03 UTC, aannenko commented on source/Tests/view-old.js
> +/**
According to the file's name, this file should not be included in this pool request as well as it should not exist in the repo.

2017-12-01 22:03 UTC, aannenko commented on source/css/style.css
> +    -webkit-border-radius: 50%;
We've agreed to support only newest browser versions. Do we still need these specific styles despite this fact?

2017-12-01 22:03 UTC, aannenko commented on source/fonts/fontawesome-webfont.svg
> +<?xml version="1.0" standalone="no"?>
Lots of new files are sent to this pool request. Can we make sure that we don't have unused files (fonts, styles, etc.) in the repo?

2017-12-01 22:03 UTC, aannenko commented on source/js/model.js
> +    let movesCounter = 1;
Please keep up with the coding style, use underscore before class-level variable names.

2017-12-01 22:03 UTC, aannenko commented on source/js/view-model.js
> +        // return this.getCurrentStatus() === 'Tie' ? 'It' : _game.state.currentPlayerName;
We do not keep redundant code, especially if it is commented out. ;)

2017-12-08 12:26 UTC, KassandraA commented
Changes are done.

2017-12-08 19:26 UTC, aannenko requested changes
Several minor things to consider:
- The scrollbar is too close to settings
- Shadows are truncated to the left and right from the controls on the Settings view
- Shadows should be more like on the mock, they should look more like a single background shadow for all elements
- The '+' button is thicker that the player rows
- Header's content moves up when the header is being resized
- The Settings button jumps left and right when you switch between Game and Settings views
- Colors are not accurate (blue, orange.)
- The gaps between cells do not match those on the mock
- In case of a narrow vertical browser window, both the Game and the Settings views shouls occupy the whole width of the window
- We have to refuse empty names for a player in the updatePlayer method of the model.js

2017-12-08 19:26 UTC, aannenko commented on source/css/style.css
> +    width: 100%;
It appears, width setting can be removed.

2017-12-13 21:22 UTC, aannenko commented
🥇

2017-12-13 21:23 UTC, aannenko approved these changes

2017-12-13 21:23 UTC, merged