Bug fixing #24
aannenko/noughts-and-crosses pull request #25
Opened 2018-01-12 13:21 UTC by KassandraA

All bugs are fixed.

2018-01-12 23:07 UTC, aannenko commented
![2018-01-13](https://user-images.githubusercontent.com/4640265/34898901-c4943d4c-f7f5-11e7-9684-09315be69cdf.png)

2018-01-12 23:08 UTC, aannenko requested changes

2018-01-12 23:08 UTC, aannenko commented on source/js/view.js
> +            symbolImg.addEventListener('click', function() {
Redundant spaces.

2018-01-12 23:08 UTC, aannenko commented on source/js/view.js
> +        if (transformer[i] === settingsTransformer) {
Redundant spaces

2018-01-12 23:08 UTC, aannenko commented on source/js/view.js
> +            settingsTransformer.style.height =  wrapper[i].offsetHeight / scale + 'px';
Redundant space.

2018-01-15 12:01 UTC, KassandraA commented
Changes are done.

2018-01-15 19:19 UTC, KassandraA commented
Changed favicon.

2018-01-15 19:28 UTC, aannenko commented
Nice job!

2018-01-15 19:28 UTC, merged