ViewModel should initialize with some data pre-set. #5
aannenko/noughts-and-crosses pull request #9
Opened 2017-03-07 18:43 UTC by KassandraA

Done it.

2017-03-08 07:43 UTC, aannenko requested changes

2017-03-08 07:43 UTC, aannenko commented on source/view-model.js
> +        for(let i = 0; i < gamePreset.players.length; i++){
Can we replace `for` with `gamePreset.players.forEach` and then simplify the internals of the cycle?

2017-03-08 07:43 UTC, aannenko commented on source/view-model.js
> +function GamePreset(){
Can we put informational (non-functional) objects in the same chunk of code? GamePreset and GameInfo have the same purpose and can be placed in the code one after the other.

2017-03-20 12:32 UTC, KassandraA commented on source/view-model.js
> +function GamePreset(){
Done

2017-03-20 12:53 UTC, KassandraA commented on source/view-model.js
> +        for(let i = 0; i < gamePreset.players.length; i++){
Done

2017-03-20 19:13 UTC, closed without merging